# Que espécie de bicho é a ciência e como separá-la do joio da pseudociência? {#sec-2}

À primeira vista, pode parecer fácil determinar o que a Ciência é e distingui-la do que não o é, ou seja, da charlatanice, da pseudociência ou de outros empreendimentos cognitivos humanos. No fundo, trata-se de reconhecer que o conhecimento científico é o conhecimento profundo, refletido e verdadeiro e distingui-lo, portanto, do conhecimento apenas aparente, do conhecimento superficial ou da falsidade. Essa, aliás, é a distinção clássica que esteve presente no pensamento ocidental desde o tempo de Parmênides: a distinção entre conhecimento (episteme) e mera opinião (doxa), ou por outras palavras, a tentativa de separar o trigo (a realidade / verdade) do joio (aparência / ilusão). Mas tivemos de esperar por Platão e pelo seu célebre Teeteto 2015) para lermos a proposta posta na boca de Sócrates, com a famosa definição de conhecimento como “crença verdadeira justificada”. E, nos 2400 anos que se seguiram, a definição aceite de conhecimento permaneceu a de Platão: “crença verdadeira justificada”. Como veremos à frente, no entanto, esta definição só foi seriamente posta em causa por Ed Gettier (1963).

## Separando o Trigo do Joio ao Longo da História: Os Diferentes Critérios de Demarcação {#sec-2-1}

### Cepticismo e Dogmatismo {#sec-2-1-1}

A filosofia grega debateu a natureza da justificação do conhecimento ainda antes de Platão e de Aristóteles. Deveria o conhecimento ter uma base empírica (referindo-se apenas aos dados dos sentidos ou à experiência, por exemplo, Epicuro) ou racional (referindo-se a justificações abstratas, a priori e/ou inatas, por exemplo, Pitágoras ou Platão)? Os céticos também se posicionaram neste debate e foram para além desta preferência por um critério racional ou empírico de justificação do verdadeiro conhecimento. Os céticos questionavam todas as justificações de conhecimento e da própria possibilidade de justificação. Tomemos como exemplo Pirro e sobretudo o seu seguidor, Sexto Empírico, autor de uma série de volumes com títulos, desde logo sugestivos, como Contra os Matemáticos, Contra os Gramáticos, Contra os Retóricos, Contra os Geómetras, Contra os Aritméticos, Contra os Astrólogos, Contra os Músicos, Contra os Lógicos, contra os Físicos, e Contra os Éticos): O objetivo de Sexto Empírico era permitir que o pensador cético visse para além das aparências e das convenções e suspendesse o julgamento (realizasse a epoché), começando a skepsis (procura) a partir do mínimo de considerações a priori. Sexto Empírico apresentou alguns modos de pensamento ardilosos. No fundo, trata-se de diferentes justificações que um dogmático (ou seja, um não-cético) adota para sustentar a sua crença. Identificar estas justificações ou modos de pensamento permite-nos, então, ir além das aparências. Mas que modos de pensamento são estes? Podemos tomar como exemplo o modo de regressão infinita, o modo de reciprocidade e o modo da hipótese, que usados em conjunto, passaram a ser conhecidos como o trilema de Agripa.[^02-capitulo2-1]

[^02-capitulo2-1]: O Trilema de Agripa volta a ser abordado ao longo da História, sendo também conhecido posteriormente como o trilema de Munchausen (nome proposto por Hans Albert na sua obra Tratado da Razão Crítica, 1985) e por Trilema de Fries (atribuído por Popper na Lógica da Descoberta Científica, 2002, embora nessa versão seja algo diferente).

Quando utiliza o modo de regressão infinita, o dogmático tenta fornecer apoio fundamentado para uma crença mas esse apoio, qualquer que seja, também necessita de apoio fundamentado e assim por diante até ao infinito e, como tal, torna-se pouco razoável defender uma crença cuja apresentação de fundamento vai necessariamente sendo sempre adiada.
Quando utiliza o modo de reciprocidade (circularidade), o dogmático cria uma cadeia de justificação em que a crença que se pretende fundamentar se torna também em fundamento e, como tal, a crença em causa passa a carecer de fundamento independente e não parece prudente adotá-la.
E quando utiliza o modo de hipótese (ou dogmático), o dogmático limita-se a afirmar a sua crença, sem apresentar qualquer fundamento. Neste modo, o dogmático não pode pretender que manter uma crença é melhor que qualquer outro palpite.
Para Sexto Empírico, o papel de um cético é identificar o modo de pensamento que um dogmático está a utilizar e fazê-lo dar-se conta do seu erro dogmático. É fácil ver como o trilema de Agripa é capaz de minar quase qualquer visão ou posição e ir além das aparências.
Para além de ser abordado por Sexto Empírico, o Trilema de Agripa também é mencionado por Aristóteles na sua obra fundamental Analíticos Posteriores do Organon IV (trad. port. de1987). Aristóteles refere-se às armadilhas desse trilema para explicar a necessidade de justificar o conhecimento científico, mas rejeita o modo de regressão infinita e o modo de circularidade e defende que o verdadeiro conhecimento necessita de certeza apodítica.[^02-capitulo2-2] É esta última característica que, para Aristóteles, identifica claramente o conhecimento e é nela que, de resto, assenta a posição da filosofia. O que separa o conhecimento de outros tipos de crenças é a certeza das suas fundações e, graças a essa certeza, a infalibilidade dos conhecimentos que delas derivam. Esta perspetiva fundacional foi a principal forma de defesa contra o ceticismo, embora, curiosamente, acabe por escolher apenas uma das alternativas do trilema de Agripa. Por isso, podemos olhar para a história da epistemologia como uma longa resposta ao ceticismo, sem grande êxito, indo de concessões parciais (por exemplo, Descartes, Kant, Wittgenstein) ou quase totais (por exemplo, Hume, Popper) até à defesa do seu evitamento puro e simples (Reid, Hegel). Mais, podemos considerar a ciência, baseada no pensamento crítico e questionamento constantes, construindo ideais de corroboração e refutação, cada mais exigentes, mas, ao mesmo tempo, aceitando a falibilidade do conhecimento humano como um projeto eminentemente cético.

[^02-capitulo2-2]: Proposição que se assume verdadeira ou falsa como uma necessidade por ser demonstrável logicamente ou autoevidente ou óbvia.

Mas voltemos às peripécias do desenvolvimento da distinção entre conhecimento verdadeiro e mera crença: Pelo menos desde o final do Império Romano e durante boa parte da Idade Média, o conhecimento verdadeiro passou a ser identificável pela sua correspondência com as afirmações e ensinamentos de algum emérito autor e/ou fonte com autoridade epistemológica considerada absoluta. Este foi o critério de conhecimento quando o dogma de referência passou a ser as Escrituras Judaico-Cristãs. Daí que as fontes de justificação epistemológica anteriormente referidas tenham encontrado um novo limite na necessidade de corresponderem às escrituras. Por exemplo, apesar de Maimonides, um dos principais filósofos medievais sefarditas, ser um confesso admirador da racionalidade e ter defendido que nenhuma verdade poderia contradizer a razão, admitia também a necessidade da compatibilização de factos incontroversos com a interpretação da Torah (ver Guia dos Perplexos, Trad. ing.). O mesmo poderíamos dizer de Averróis (Belo, 2007), um dos maiores filósofos neoplatónico islâmico relativamente à não contradição com o Corão (A Incoerência da Incoerência) ou de S. Tomás de Aquino que defendia a autoridade suprema das Escrituras e que doutrinas que repugnassem à autoridade das Escrituras deveriam ser rejeitadas (Suma Teológica). Como afirma Aquino: “é evidente que algo de falso nunca pode ser [contido] sob o sentido literal da Sagrada Escritura” (Summa Theologiae, I, r, ro, ad 3). Esta é a chamada tese da Inerrância da Bíblia (ainda hoje defendida por alguns teólogos, ver Nicholls, 1980).
Claro que o problema prático do dogmatismo é o das fontes de referência que se desdizem ou o das múltiplas interpretações contrárias da mesma fonte. Aí entrava o chamado probabilismo na chamada casuística. É um princípio avançado pela ordem jesuíta no século XVI e que vigorou até ao século XVII. O que deve ser feito quando as autoridades epistemológicas, especialmente os Pais da Igreja, não concordam entre si? O problema tornou-se premente no final do Renascimento à medida que foi sendo proposta um número cada vez maior de interpretações das fontes dogmáticas. Basicamente, havia duas possibilidades. Para resolver o conflito, poderíamos reduzir as autoridades que reconhecemos, mantendo-nos apenas pelo recurso às escrituras e iluminados pela luz natural da razão. Ou poderíamos considerar um leque de autoridades mais vasto, mas ao decidir entre elas, devemos considerar os efeitos sociais e morais da adoção das suas várias doutrinas e optar pela que promete promover os efeitos mais benéficos. Curiosamente, e optando claramente pela segunda alternativa, o probabilismo na teologia não dizia que, quando as autoridades entram em conflito, devemos seguir a opinião mais provável. O probabilismo dizia que se pode seguir uma opinião provável ou outra, de acordo com os efeitos mais favoráveis para a sociedade da implementação social dessas opiniões, mesmo que uma opinião selecionada seja menos provável do que outras. A palavra "provável" aqui não significa "bem apoiada por provas". Significa apoiada por, pelo menos, uma autoridade epistemológica. Quer isto dizer que em caso de dúvida, sobre a melhor forma de agir, poder-se-á, de acordo com os probabilistas, seguir um curso de ação que é recomendado por alguma autoridade e cuja implementação é considerada mais conveniente ou benévola, mesmo quando autoridades superiores em estatuto ou número aconselham o caminho oposto de ação. Mas, como Pascal argumentou nas Provinciais, é possível e assim aconteceu que os probabilistas optassem primeiro por um rumo de ação dada a conveniência social e moral e depois encontrassem um texto antigo que pudesse ser interpretado como aprovação desse curso de ação. Na prática, seria ter um critério de verdade que se adaptasse às crenças e necessidades de cada teólogo ou filósofo. Com isto, Pascal desferiu um golpe decisivo nas versões casuísticas e probabilísticas do dogmatismo, tornando-se também num dos grandes contribuidores para a versão mais moderna do racionalismo de que falaremos adiante (em conjunto com Descartes, Leibnitz, Espinoza e Kant) e até o precursor da teoria de decisão e da teoria dos jogos na sua célebre aposta sobre a existência de Deus (Pensamentos).

### Empirismo {#sec-2-1-2}

O critério empirista de verdade de uma afirmação ou de uma teoria é o da sua correspondência com os dados dos sentidos, a observação e/ou a experiência. Daí que, segundo este critério, se rejeite tudo o que não possa ser justificado pela evidência de dados ou factos. Tal era a posição do primeiro dos grandes filósofos empiristas britânicos, John Locke. Segundo Locke (Ensaio Acerca do Entendimento Humano), as mentes humanas nascem como tábuas rasas ou folhas em branco que só a experiência pode preencher. Francis Bacon, outro empirista, preconizava no Novum Organon que, para que os filósofos não se enganem a si próprios seguindo ídolos (ideias pré-concebidas e pouco perscrutadas), só os conhecimentos que tivessem origem em induções morosas e cuidadosamente escrutinadas é que deveriam ser tomados como válidos. Por exemplo, induções que partissem de muitos exemplos, todos partilhando a mesma característica essencial, permitindo assim, supostamente, a inferência de generalidade. Esta posição mistura empirismo e ceticismo e faz com que muitos o considerem como o pai do método científico. Contudo, David Hume (no Investigação sobre o Entendimento Humano), também um empirista, mas talvez sobretudo, o mais importante dos céticos, questionava a justificação das inferências indutivas, ou seja, questiona a razão de usarmos a nossa experiência particular como base de qualquer generalização ou da identificação de causas. Hume defendia que só conhecemos conjunções mais ou menos constantes de semelhanças, de contiguidades ou de precedências e que partir de conjunções constantes para a identificação de causas ou leis, é partir da observação de casos que conhecemos para a caracterização de casos que não conhecemos. A discrepância entre os casos que conhecemos e os casos que pretendemos caracterizar impossibilita qualquer justificação racional. E, se nos sentimos recompensados a fazê-lo, tal é apenas uma forma de superstição que só pode provir da nossa ascendência animal. Este é o famoso argumento de Hume contra a possibilidade de justificação das inferências indutivas ou causais, que inquietou e inquieta gerações de filósofos e cientistas (ver mais à frente a nota sobre a diferença entre indução e dedução).

### Racionalismo {#sec-2-1-3}

O critério racionalista da verdade de uma afirmação ou de uma teoria é o da sua natureza internamente consistente e dedutível a partir de um conjunto de postulados universais e/ou necessariamente verdadeiros (axiomas autoevidentes). O grande modelo dos racionalistas é a Geometria de Euclides que, a partir de um conjunto de pressupostos simples e autoevidentes (axiomas), desenvolve um conjunto de teoremas deduzíveis desses pressupostos e constitui um sistema lógico-formal impressionante (mas nunca completo, ver nota adiante sobre o segundo teorema de Göddel). Assim, a justificação de uma afirmação teria sempre de ser demonstrada, quer dizer, ter-se-ia de mostrar que essa afirmação era deduzível de pressupostos universais e/ou autoevidentes. A inferência lógica, base da justificação do conhecimento no racionalismo, não estaria, contudo, disponível para justificar os pressupostos ou axiomas de onde partem as inferências lógicas. Esses teriam de ser encontrados por meios extra-lógicos com base na sua universalidade ou no consenso generalizado que merecessem. Daqui nascem os célebres argumentos “cogito” na identificação dessas verdades indesmentíveis, o cogito ergo sum (penso logo existo) de Descartes e o de Santo Agostinho, si fallor, sum (erro logo existo) mas também os a priori que Kant defendeu serem indispensáveis à própria possibilidade de experiência e de aprender com ela – as categorias sensíveis a priori de tempo, e espaço. Além destas, Kant identificava ainda as categorias a priori do entendimento, quantidade (unidade, pluralidade e totalidade), qualidade (realidade, negação e limitação), relação (substância, causalidade e comunidade) e modalidade (possibilidade, existência e necessidade). Estas categorias a priori do entendimento poderiam ser preenchidas ou instanciadas pela experiência, mas não por ela formadas ou destruídas (Crítica da Razão Pura / Prolegómenos a Toda a Metafísica Futura). Para Kant, o conhecimento seria divisível em proposições sintéticas e analíticas. As proposições analíticas eram consideradas "verdadeiras em virtude de significados e independentemente do facto", sendo muitas vezes derivadas das categorias a priori e necessárias. Já para as proposições sintéticas, a verdade é um valor que tem de ser determinado empiricamente. Numa aceção mais contemporânea, as proposições analíticas são tomadas como verdadeiras não por serem necessárias, mas por serem tautológicas (por exemplo, todos os homens solteiros não são casados). A proposta de categorias a priori e necessárias para a possibilidade da própria experiência e aprendizagem e que poderiam servir de base a um sistema dedutivo era, de certo modo, a resposta de Kant e dos racionalistas ao ceticismo de Hume.


### Os Dois Grandes Problemas dos Critérios Clássicos Atrás Descritos {#sec-2-1-4}

- A indução não pode alcançar justificação racional porque implica atribuir características de instâncias que conhecemos a instâncias que não conhecemos, que existiram no passado, que só existirão no futuro ou até que nunca existirão. A inferência indutiva de uma lei natural (ver em Hempel a noção de lei natural) como “todos os cisnes são brancos” realizada a partir dos cisnes que conhecemos, implica que os cisnes que nascerão serão brancos ou que, em lugares em que nunca existiram cisnes, se tivessem existido, teriam sido brancos. Ora é impossível justificar racionalmente tal inferência: é impossível garantir que, se as premissas forem verdadeiras (no caso, as inúmeras observações de cisnes brancos) então, a inferência é necessariamente verdadeira (todos os cisnes são brancos). E um dia descobriram-se cisnes negros na Austrália…
- É muito discutível e nunca consensual a existência de postulados universais e necessários. Por exemplo, os postulados de cogito podem apenas ter uma aplicação válida ao próprio (solipsista) mas não garantem justificação racional para qualquer generalização a outros seres. E, quanto a Kant, mesmo que aceitemos que não pode haver conhecimento de um objeto sem que ele seja tomado como uma instância de uma ou mais categorias a priori, podemos divergir sobre a natureza e identidade dessas categorias. Consideremos, por exemplo, a noção de que o espaço euclidiano é necessário e prévio a qualquer aprendizagem pela experiência. Apesar de plausível, tal a priori é difícil de sustentar, dada a hipótese de a natureza euclidiana do espaço no nosso universo ter sido refutada (a partir de evidência obtida a partir da teoria da relatividade, o nosso universo existe num espaço curvo de natureza Riemanniana). É claro que é sempre possível aceitar determinados postulados sem conceder, tentando identificar os teoremas que podem ser demonstrados a partir desses postulados, e construir arbitrariamente um sistema formal, tomando a geometria euclidiana como referência. Contudo não é garantido que tal aceitação transitória de postulados arbitrários contribua para o nosso conhecimento sintético (ver acima) nem que não existam teoremas verdadeiros que não sejam demonstráveis (ver nota adiante sobre teorema de Göddel).
Mas, talvez, juntando as duas fraquezas, essas fraquezas se possam tornar numa força, como veremos mais à frente.

### A Nova Importância de um Critério de Demarcação em Duas Perguntas: Como Proteger a Sociedade das Pseudociências Mascaradas de Ciência? E Para Onde Vão as Teorias Científicas Após a Refutação? {#sec-2-1-5}

As leis do movimento e da gravitação universal de Newton, constituíram provavelmente o pináculo da ciência pré-moderna e um sinal da revolução científica em plena eclosão. O êxito dessas teorias teve inúmeros impactos na sociedade do seu tempo e, naturalmente, também na própria Filosofia. Por um lado, mostrou como a Ciência é um domínio que não pode ser ignorado se se quiser compreender o que é o conhecimento e como é adquirido. Por outro, mostrou que se poderia ignorar as preocupações céticas, visto que o conhecimento parecia ser adquirível e utilizável com enorme êxito, mesmo se fosse dificilmente caracterizável ou justificável.
Quanto ao primeiro aspeto, a importância da Ciência para compreender e adquirir conhecimento, o próprio êxito da ciência fez eclodir o aparecimento de imitações, quer dizer, de abordagens com pouco a ver com a ciência, mas reclamando esse mesmo estatuto. Por exemplo, foi um contemporâneo de Hume, Samuel Hahnemann (1755-1843), que propôs uma das famosas pseudociências com pretensão de ciência – a Homeopatia. E a tendência apenas se acentuou, com o aparecimento de novos e ainda mais populares heróis científicos (por exemplo, Darwin, Einstein) nos séculos seguintes. Algumas das ideologias políticas passaram a apresentar-se como científicas (marxismo, racismo), algumas religiões ou teorias de base religiosa fizeram o mesmo (criacionismo, cientologia). Por isso, a demarcação da ciência deixou a torre de cristal da filosofia e passou a ser uma questão de educação formal e informal, de saúde pública e garantia do bom funcionamento das democracias.
Relativamente ao segundo aspeto relativo ao êxito de Newton face às preocupações céticas, basta recordar que a vontade de ignorar o ceticismo sempre caracterizou muitos filósofos. Hegel, por exemplo, afirmou que “o ceticismo é o adversário invencível da Filosofia”, é irrecusável, e a atitude filosófica só pode ser a do ignorar (ver Thomas Reid para posições de evitação do ceticismo). Daí que um exemplo glorioso de produção e acumulação de conhecimentos verdadeiros acerca do mundo representava uma grande forma de calar os céticos. Claro que o problema de Hume, relativo à impossibilidade de justificar das inferências indutivas, foi colocado pouco depois, o que não deixou nenhum filósofo ignorar o ceticismo de forma completamente tranquila por muito tempo. Mas o pior estaria para vir. Não só o exemplo de Newton era insuficiente para ignorar completamente o ceticismo, como ainda por cima, as leis do movimento e da gravitação universal de Newton eram falsas e foram refutadas por dados obtidos a partir da teoria da relatividade de Einstein. Teria a principal teoria de Newton deixado de ser científica? Ou uma teoria científica podia ser falsa? No fundo, tornava-se necessário responder à pergunta do título desta seção – para onde vão as teorias científicas quando são refutadas? Para responder a esta pergunta, foi necessária a emergência de novos critérios de demarcação e o desenvolvimento da Epistemologia das Ciências.

### O Círculo de Viena e o Positivismo Lógico: O Advento da Epistemologia das Ciências e dos Epistemólogos Profissionais {#sec-2-1-6}

O Círculo de Viena foi um movimento sobretudo de filósofos que se reunia entre 1924 e 1936 na Universidade de Viena, presidido por Moritz Schlick. A emergência do fascismo na Áustria e a anexação desta pela Alemanha Nazi, forçaram a maioria dos membros do Círculo de Viena a emigrar. O assassinato de Schlick em 1936 por um ex-aluno, marcou o fim simbólico do movimento. O empirismo lógico deve ser considerado como um movimento e não como uma doutrina, porque não existe provavelmente nenhuma ideia filosófica ou posição importante que seja partilhada por todos os aderentes do Círculo de Viena. O que emprestou coerência ao movimento foi uma preocupação comum com as relações entre ciência e filosofia. Preocupação que levou à emergência de filósofos profissionais da ciência (vindos quer da filosofia quer das ciências).
As abordagens filosóficas do Círculo de Viena foram coletivamente denominadas como empirismo ou positivismo lógico. O seu grande projeto foi o de fazer com que a filosofia tomasse a sério a ciência e se tornasse, ela própria, numa disciplina científica com a ajuda da lógica moderna. Este movimento foi grandemente inspirado pelas teses de Wittgenstein sobre o significado e a verdade das proposições, apresentadas no seu célebre Tratado Lógico-Filosófico: “Compreender uma proposição, quer dizer, saber a que se refere, e se é ela verdadeira. (Pode-se então compreendê-la sem saber se ela é verdadeira.) Compreendemo-la se compreendermos as suas partes constituintes.” [§ 4.024] O Círculo de Viena tomou como sua esta noção sobre o significado de uma proposição e designou-o como princípio da verificabilidade. Assim segundo Schlick (1936), o princípio de verificabilidade afirma que “indicar o significado de uma proposição equivale a indicar as regras segundo as quais a proposição deve ser utilizada, e isto é o mesmo que indicar a forma como pode ser verificada (ou falsificada). O significado de uma proposição é o método da sua verificação”. Mas Wittgenstein toma o critério de verificabilidade não só como critério do significado de uma proposição, mas também como noção guia do seu projeto de filosofia e critério de delimitação entre ciência e metafísica. Assim: “O método correto da filosofia seria o seguinte: só dizer o que pode ser dito, i.e., as proposições das ciências naturais – e portanto sem nada a ver com a Filosofia – e depois, quando alguém quisesse dizer algo de metafísico, mostrar-lhe que nas suas proposições existem sinais aos quais não foram dados uma denotação" [§ 6.3]. Portanto, uma proposição só teria significado se fosse verificável e o conhecimento científico seria o domínio próprio do universo das proposições verificáveis (ou testáveis), proposições cujo valor de verdade pudesse ser determinado pela confrontação empírica. (Nota, note-se que o que se exigia era que as proposições fossem testáveis, não que fossem verdadeiras, nem que já tivessem sido testadas).

::: {.topico-box}
**CAIXA 1 - O Operacionalismo, o Princípio da Incerteza e o Comportamentalismo**

Talvez a forma mais radical do critério de verificabilidade se deva a Bridgeman e ao seu “operacionalismo”:
*“aquilo que queremos expressar, por qualquer conceito, nada mais é do que um conjunto de operações; o conceito é sinónimo do conjunto de operações correspondente. Se o conceito for físico, como o conceito de comprimento, as operações são operações físicas efetivas, nomeadamente, aquelas pelas quais o comprimento é medido; se o conceito é mental, como o conceito de continuidade matemática, as operações são operações mentais, nomeadamente aquelas pelas quais determinamos se um dado agregado de magnitudes é contínuo. Não se pretende insinuar que existe uma divisão pura e dura entre conceitos físicos e mentais, ou que um tipo de conceito nem sempre contém um elemento do outro; esta classificação do conceito não é importante para as nossas considerações futuras. Temos de exigir que o conjunto de operações equivalente a qualquer conceito seja um conjunto único, pois caso contrário existem possibilidades de ambiguidade em aplicações práticas que não podemos admitir.”*
<p style="text-align: right;">(Bridgman 1927)</p>

Mais, Bridgman sublinhou que os conceitos não se estenderam automaticamente para além dos domínios em que foram originalmente definidos e, como tal, falar de conceitos de forma que transcende as operações que fazemos para os medir ou manipular é tornar tais conceitos vazios de significado.
Esta abordagem corresponde talvez mais perfeitamente ao ceticismo de Pirro e Sexto Empírico e à imposição de uma epochê (suspensão do juízo) mas, ao invés de provocar a ataraxia[^02-capitulo2-3] do operacionalista, o operacionalismo conduz o operacionalista a algumas surpresas. Na física, por exemplo, o princípio da complementaridade quântica de Niels Bohr (nota, físico dinamarquês, 1885-1962, principal proponente da interpretação de Copenhaga da Mecânica Quântica) assevera que a natureza da matéria e da radiação é dual e que os aspetos ondulatório e corpuscular não são contraditórios, mas complementares. E a razão é a de que as naturezas corpuscular e ondulatória da luz são ambas detetáveis, mas apenas o são separadamente, de acordo com o tipo de experiência. Assim, na experiência da dupla fenda de Young, os resultados sugerem que a natureza da luz é ondulatória, ao passo que na experiência do efeito fotoelétrico, os resultados sugerem uma natureza corpuscular, como demonstrou Einstein. Tal contradição é aceitável porque para Bohr, a natureza da luz não pode ser separada dos instrumentos de medição que criam o contexto em que a luz ao ser medida se comporta (operacionalismo, ver por exemplo Rosenfeld, 1953).

[^02-capitulo2-3]: Tranquilidade de espírito ou equanimidade, estado desejado pelos céticos pirronistas, alcançável pela *epochê*.

Note-se, contudo, que, sem pressupostos operacionalistas, tal contradição não seria atribuível à natureza da luz mas a limitações dos instrumentos e contextos experimentais em que é medida. Daí que, ao invés da aceitação da complementaridade, esperar-se-ia que uma teoria da luz elucidasse como a natureza da luz leva a resultados que sugerem uma natureza corpuscular ou ondulatória consoante as condições experimentais em que é medida (argumento semelhante é apresentado por Einstein, Podolsky & Rosen 1935). O princípio da incerteza e os saltos quânticos de Heisenberg ou o paradoxo do gato de Schroedinger decorrem da mesma aceitação radical do operacionalismo.
Mas onde a influência de Bridgman foi talvez ainda mais importante foi na Psicologia. Em que toda uma escola de pensamento, o comportamentalismo de Skinner, fez depender a aceitação de qualquer conceito à possibilidade da sua tradução em procedimentos experimentais ou em que o desempenho num teste relacionada com uma competência que se quer medir, passa a corresponder diretamente a essa competência (“inteligência é os que os testes testam”, Boring, 1923) e diferentes testes nunca poderiam medir a mesma competência (Bridgman, 1945).
:::

O Círculo de Viena combinou empirismo e racionalismo numa abordagem inovadora ao conhecimento, integrando observações sistematizadas em leis gerais e um sistema formal e consequências logicamente válidas dessas leis gerais. Assim, o conhecimento adviria da enunciação de leis universais derivadas de observação sistemática (empirismo) e da dedução de teorias (racionalismo) que demonstrassem como as proposições que formam um determinado domínio científico podem ser deduzidas dessas leis universais. Assim, para o Círculo de Viena, uma teoria científica deveria ser um sistema dedutivo com axiomas que obtém uma interpretação empírica através de regras de correspondência. Essas regras estabelecem uma correlação entre os objetos ou processos reais e os conceitos abstratos da teoria. A linguagem de uma teoria inclui, então, dois tipos de proposições: observacional e teórica. Proposições observacionais denotam objetos ou propriedades que podem ser diretamente observados ou medidos, enquanto proposições teóricas denotam objetos ou propriedades que não podemos observar ou medir, apenas inferir de observações diretas. A distinção observacional/teórica assemelha-se à distinção kantiana entre proposições analíticas e sintéticas. As proposições analíticas são verdadeiras a priori e a sua verdade baseia-se nas regras da linguagem; pelo contrário, as proposições sintéticas dependem da experiência e a sua verdade só pode ser reconhecida através da experiência. Idealmente, as teorias científicas deveriam conter apenas proposições de um destes dois tipos, mas, nas teorias científicas, há muitas proposições teóricas que não são verificáveis nem necessariamente verdadeiras. Estas proposições carecem de significado segundo o critério da verificabilidade. Para expurgar as teorias científicas de proposições destituídas de significado, pode tentar-se eliminá-las ou tentar "reduzir" as "proposições teóricas" a "proposições observacionais". As proposições teóricas que pertencem à linguagem abstrata de uma teoria científica devem ser explicitamente definíveis numa linguagem restrita cujas proposições descrevem apenas o que é diretamente observável.
Neste sentido, segundo o Círculo de Viena, o que distingue proposições científicas e não científicas é a verificabilidade das primeiras. Assim, as proposições presentes na linguagem científica são proposições sintéticas verificáveis ou analíticas (dedutivamente válidas) e muitas das proposições sintéticas das linguagens não-científicas podem ser sintéticas, mas inverificáveis, ou seja, sem significado.
Mais tarde, Carnap (1966, n’Os Fundamentos Filosóficos da Física) propôs uma abordagem ligeiramente diferente à distinção observacional-teórica. Agora, o ponto de partida é a diferença entre leis empíricas e teóricas. É possível confirmar (ou refutar) diretamente uma lei empírica, enquanto uma lei teórica só pode ser testada através das leis empíricas que lhe são consequentes. Além disso, uma lei empírica explica factos enquanto uma lei teórica explica leis empíricas. Assim, existiriam três níveis:
a) Factos empíricos: estes são expressos por "relatos diretos de observação"
b) Leis empíricas: Generalizações simples que podemos confirmar diretamente por observação. Explicam os factos e são utilizadas para prever factos empíricos, deduzindo proposições de observação de leis e proposições de condições iniciais.
c) Leis teóricas: Princípios gerais que podemos usar para explicar leis empíricas, deduzindo a partir deles leis empíricas, conhecidas ou novas.
As leis empíricas incluem apenas proposições observacionais, enquanto proposições teóricas ocorrem apenas em leis teóricas.

::: {.topico-box}
**CAIXA 2 - O Critério de Verificabilidade e o Instrumentalismo: O Positivismo-Lógico e o Ceticismo**

O instrumentalismo é uma posição que se considera próxima do positivismo-lógico, mas que o antecipou numa vintena de anos. Foi originalmente introduzida pelo físico francês Pierre Duhem (1906, La théorie physique: Son Objet, sa Structure), e defendida por cientistas como Ernest Mach e William Whewell, entre outros. De acordo com os instrumentalistas, uma teoria científica bem-sucedida não revela nada de verdadeiro ou falso sobre objetos, propriedades ou processos não-observáveis da natureza. Uma teoria científica é apenas uma ferramenta que permite fazer previsões empíricas acerca de um dado domínio da natureza, identificando regularidades observáveis ou formulando leis, enquanto as próprias teorias que permitiram identificar essas regularidades ou formular tais leis não revelam necessariamente quaisquer mecanismos ocultos da natureza que subjazem a essas leis ou regularidades e que de alguma forma as explicam.
O instrumentalismo evita o debate sobre se, por exemplo, os seis paladares (flavors) dos quarks (cima, baixo, estranho, charme, fundo e topo) são entidades que gozam de existência individual, sobre as equações que descrevem diferentes estados de um gás, sobre os modos de excitação de diferentes regiões de um campo, ou qualquer outra coisa. O instrumentalismo sustenta que os termos teóricos só precisam de ser úteis se forem capazes de prever fenómenos relevantes, independentemente de poderem ser verdadeiros ou ficções convenientes.
Como veremos adiante, as críticas ao positivismo lógico atingem também o instrumentalismo e o operacionalismo.
:::

### Popper e a Superioridade Lógica da Refutação em Ciência: Falibilismo e Ceticismo {#sec-2-1-7}

Karl Raimund Popper (1902 – 1994) foi um dos maiores epistemólogos do século XX. Nasceu em 1902 em Viena e antes de se dedicar completamente à Filosofia foi ativista político de esquerda, professor primário, marceneiro, músico e tirou um curso de Psicologia onde foi examinado por Moritz Schlick em Filosofia e por Karl Buhler em Psicologia na sua prova oral final. No final dos anos 20, um tio também filósofo, Walter Schiff, trouxe-o aos debates do Círculo de Viena e, a breve trecho, Popper começou a escrever umas notas examinando criticamente as teses que estavam em voga na altura, nomeadamente, as de Wittgenstein. Herbert Feigl, um colega de Popper da Universidade convenceu Popper a tentar publicá-las e Moritz Schlick e Philipp Frank aceitaram publicá-las em 1933 na principal coleção do Círculo, a Escritos na Conceção Científica do Mundo, editada pela editora Julius Springer de Viena. Popper apelidou essas notas como Os Dois Problemas Fundamentais em Epistemologia mas a editora considerou o 1º volume demasiado grande e Popper foi forçado a condensar os dois volumes da obra num único. Mesmo assim, a obra foi considerada grande demais e o tio de Popper, Walter Schiff, criou um livro de excertos, publicado em alemão em 1934 e traduzido para inglês cerca de 20 anos depois, que acabou por se chamar A Lógica da Descoberta Científica. Foi e é uma das obras decisivas da Epistemologia. As notas originais só haveriam de ser publicadas em alemão em 1978 e em inglês em 2009 (com o 2º volume incompleto, porque acabou por nunca ser completamente escrito).
Os dois problemas da Epistemologia são, segundo Popper, a Indução e a Demarcação ou como ele os designou, o problema de Hume e o problema de Kant. Popper afirma que resolveu o problema de Hume muito cedo na sua vida, mas que não achou que valesse a pena publicar tal solução porque ela já tinha sido antecipada por muitos outros filósofos como, por exemplo, Sexto Empírico, no sentido em que a resposta à pergunta “que justificação racional existe para a indução?” é: “nenhuma”. Só quando Popper compreendeu que exista uma relação entre o problema de Hume e o do Kant é que considerou existir algo de novo. Passemos então uma breve discussão destes dois problemas e das suas soluções segundo Popper.

::: {.divider-box}
O problema de Hume
(o primeiro problema de Popper)
:::

Como já vimos, segundo Hume, a indução implica a generalização das características dos casos que observamos para a caracterização de casos que nunca observamos. Como tal, nunca está garantido que, mesmo partindo de premissas verdadeiras, uma inferência indutiva seja verdadeira. Segundo Hume, a razão para acreditarmos em tais inferências, tem mais quer ver com as nossas limitações cognitivas do que com qualquer argumento racional ou evidência empírica que apoie tais inferências. Bertrand Russell, ilustrava o problema de Hume com uma história cheia de moral, a história do peru indutivista:
“Este peru descobriu que, na sua primeira manhã na fazenda de perus, foi alimentado às 9 da manhã. No entanto, sendo o peru, um bom peru indutivista, não se permitiu conclusões precipitadas. Esperou até ter recolhido um grande número de observações sobre o facto de ter sido alimentado às 9 da manhã e recolheu estas observações sob uma grande variedade de circunstâncias – às quartas e quintas-feiras, em dias quentes e dias frios, em dias chuvosos e dias secos. Todos os dias, acrescentou outra instância à sua lista de observações. Finalmente, o carácter sistemático e exaustivo da sua lista de observações tornou-se indubitável e o peru sentiu-se confiante na realização da seguinte inferência indutiva: "Sou sempre alimentado às 9h da manhã.". Infelizmente, esta conclusão mostrou-se claramente falsa quando, na véspera de Natal, em vez de ser alimentado, lhe cortaram a garganta. Moral: Uma inferência indutiva mesmo com premissas verdadeiras pode sempre conduzir a uma falsa conclusão.”
Mas a falta de justificação racional para a indução só se torna verdadeiramente problemática para quem quer assentar como Bacon o método científico na indução, ou de uma forma geral, para quem pretende argumentar que as teorias, leis, generalizações, ou mais geralmente, os conhecimentos científicos têm necessariamente de ter uma base empírica que lhes permita partir do particular e alcançar o geral. Ou seja, a falta de justificação racional para a indução transtorna especificamente os indutivistas mas também os empiristas no geral. Popper deixa cair os primeiros e vem em socorro dos segundos. Assim, o fundamento empírico da ciência não advém da indução mas sim da dedução, ou dizendo de uma forma mais prosaica, vem do método de tentativa e erro (o falibilismo).[^02-capitulo2-4] É de notar que uma indução é dedutivamente inválida, senão observe-se o seguinte silogismo:

[^02-capitulo2-4]: Como já defendia entre outros, Francisco Sanches, filósofo, médico e matemático português do séc. XVI)

::: {.exemplo-box}
**Exemplo 1**

Todos os cisnes que observei até agora são brancos (Xi)
Xi+1 é um cisne que ainda não observei,

Logo, Xi+1 é branco
:::

Um cuidador de cisnes europeu que nunca tivesse ido à Austrália poderia sentir-se justificado a fazer tal indução depois de viver uma vida rodeado de cisnes brancos, mas tal não garantia que, em lugares onde o tratador nunca tivesse ido, não os houvesse. E havia, na Austrália.
Ou tomando um exemplo, mais próximo da investigação científica:

::: {.exemplo-box}
**Exemplo 2**

Se a teoria T for verdadeira, então a previsão P verificar-se-á
P verificou-se,

Logo, a minha teoria é verdadeira
:::

Aqui o problema é que mesmo que T preveja P, pode haver sempre outras teorias que façam a mesma predição (de um ponto de vista técnico, existe mesmo um número infinito de teorias que o fazem) e, pelo menos relativamente às teorias contrárias, ou só uma delas é verdadeira (e essa teoria pode não ser T) ou são todas falsas. Esta inferência tem a forma de um silogismo, mas é um silogismo inválido, quer dizer, é um silogismo em que a verdade das premissas não se transmite necessariamente à conclusão, é a chamada falácia da afirmação do consequente. Vejamos o mesmo silogismo relativo a assuntos mais comezinhos, de modo que a sua invalidade seja ainda mais óbvia:

::: {.exemplo-box}
**Exemplo 3**

Se for eleito deputado, então apanharei o autocarro 727 (que passa em S. Bento) no dia de tomada de posse dos deputados da nova assembleia.
Apanhei o autocarro 727 no dia de tomada de posse dos deputados da nova assembleia.

Logo, fui eleito deputado
(por acaso não, nem concorri a deputado, fui aos pastéis de Belém, o 727 também passa por lá)
:::

Popper argumenta que, apesar de se tratar de uma conclusão inválida, essa conclusão não impede que a ciência se desenvolva a partir de uma base empírica, senão vejamos.

::: {.exemplo-box}
**Exemplo 4**

Se a teoria T for verdadeira, então a previsão P verificar-se-á
P não se verificou,

Logo, a minha teoria é falsa
:::

Repara-se que, neste caso, a inferência corresponde a uma inferência válida, o Modus Tollens, e é válida porque se as premissas forem verdadeiras, a conclusão será necessariamente verdadeira. Vejam o mesmo tópico de há pouco (S. Bento) neste tipo de silogismo:

::: {.exemplo-box}
**Exemplo 5**

Se for eleito deputado, então apanharei o autocarro 727 (que passa em S. Bento) no dia de tomada de posse dos deputados da nova assembleia.
Não apanhei o autocarro 727 no dia de tomada de posse dos deputados da nova assembleia.

Logo, não fui eleito deputado.
(aqui se as premissas forem verdadeiras, a conclusão terá de ser verdadeira e, portanto, o silogismo é válido)
:::

Portanto, a verdadeira base empírica da ciência não advém da confirmação das teorias quando confrontadas com os dados, mas sim da tentativa-e-erro, da rejeição das teorias quando as suas previsões falham empiricamente. Neste sentido, Popper contesta o método científico baconiano, com algum humor. Assim nas palavras de Popper:
“Começo, regra geral, as minhas lições sobre Método Científico dizendo aos meus alunos que o método científico não existe. Acrescento que tenho obrigação de saber isso, tendo eu sido, durante algum tempo, pelo menos, o único professor desse inexistente assunto em toda a comunidade britânica. [...] Tendo, então, explicado aos meus alunos que não há essa coisa que seria o método científico, apresso-me a começar o meu discurso, e ficamos ocupadíssimos. Pois um ano mal chega para roçar a superfície mesmo de um assunto inexistente.”
Adiante, Popper esclarece a inexistência do método científico, no sentido em que: “Não há um método para descobrir uma teoria científica. Não há um método para averiguar a verdade de uma hipótese científica, quer dizer não há um método de verificação. Não há um método para determinar se uma hipótese é “provável” ou “provavelmente verdadeira”
<p style="text-align: right;">Karl R. Popper (O Realismo e o Objetivo da Ciência)</p>

Como vemos, Popper defendeu que o conhecimento científico e todo o conhecimento é conjetural e falível, quer dizer, Popper abandona a possibilidade de justificar o conhecimento (i.e., defende uma perspetiva não-justificacionista).
Mas alguns seis anos após a publicação da Lógica da Descoberta Científica, surge um desafio ainda mais inquietante para as certezas humanas: o desafio de Gettier (1963) e a pequena indústria filosófica gerada pelo seu artigo – a ideia de que mesmo uma crença verdadeira justificada poderia não corresponder a verdadeiro conhecimento. Ou seja, se admitirmos a posição de Popper, aceitamos que o conhecimento humano é necessariamente não-justificável. Mas se aceitarmos a crítica de Gettier a essa noção de conhecimento como crença verdadeira justificada, passamos a admitir que mesmo que se pudessem justificar crenças verdadeiras, essas crenças poderiam não corresponder a verdadeiro conhecimento (ver Caixa 3, Os Casos Gettier).

::: {.topico-box}
**CAIXA 3 - Os Casos Gettier**

Edmund Gettier era um jovem filósofo americano que procurava alcançar o provimento definitivo da sua posição académica. A produção académica (isto é, a publicação de artigos em revistas da sua especialidade académica e que sejam muito citados pelos pares) é fundamental para se alcançar um vínculo. Infelizmente, o seu registo de publicações era muito reduzido e a data da decisão sobre o seu provimento aproximava-se a grande velocidade. Gettier precisava de algo sobre o qual escrever, algo que fosse interessante, publicável e, acima de tudo, algo que pudesse ser escrito muito rapidamente. Num inusitado impulso, Gettier escreveu um pequeno artigo de três páginas descrevendo sua objeção à visão do conhecimento como “crença verdadeira justificada” e enviou-o para a
HIPÓTESE, CONTRASTE, GENERALIZAÇÃO E CONTRA-EXEMPLO 57
conceituada revista de filosofia Analysis. Foi publicado em 1963 e criou a tempestade perfeita.
No seu artigo original, Gettier (1963) apresentou casos hipotéticos em que uma crença verdadeira justificada não correspondia a verdadeiro conhecimento. A partir daí construir casos hipotéticos desse tipo tornou-se uma pequena indústria filosófica e, por isso, abaixo adapto e simplifico um dos meus casos preferidos da autoria de Goldman (1976), o chamado caso do “condado dos falsos celeiros”.
O Henrique está a passear de carro com o filho pelo campo. Para a edificação do menino, Henrique identifica vários objetos na paisagem à medida que vão passando por eles. "Isso é uma vaca" diz Henrique.: "Isso é um trator", "Isso é um silo", "Isso é um celeiro", etc. O Henrique não tem dúvidas sobre a identidade desses objetos; em particular, ele não duvida que o último objeto mencionado é um celeiro, o que, de facto, é. Cada um dos objetos identificados tem características distintivas que os identificam. Além disso, cada objeto está totalmente à vista, o Henrique tem excelente visão, e ele tem tempo suficiente para os olhar com razoável cuidado, já que há pouco trânsito para o distrair. Suponhamos, contudo, de que somos informados de que o Henrique sem se ter dado conta, acabou de entrar num condado que está cheio de fac-símiles de celeiros, feitos de papel machê. Estes fac-símiles, da estrada, parecem exatamente como celeiros, mas são realmente apenas fachadas, sem paredes ou interiores, inúteis como celeiros. Eles são habilmente construídos para que os viajantes invariavelmente os confundam com celeiros. No entanto, por acaso, o edifício apontado por Henrique é um verdadeiro celeiro. Mas se o objeto naquele local fosse um fac-símile, ele tê-lo-ia confundido com um celeiro. Tendo em conta esta
CAPÍTULO 2 – QUE ESPÉCIE DE BICHO É A CIÊNCIA 58 E COMO SEPARÁ-LA DA PSEUDOCIÊNCIA?
nova informação, dificilmente poderíamos afirmar que a identificação do verdadeiro celeiro, em si, reflita algum conhecimento intrínseco de Henrique sobre celeiros.
E, no entanto, a crença que Henrique comunicou ao filho é verdadeira. Mais, o Henrique poderia justificar a sua crença no facto dos celeiros terem características distintivas e diagnósticas que ele detetou naquele objeto. Claro que, depois de Hume, sabemos que essa justificação é indutiva e, portanto, não garante a verdade da conclusão. Mas vamos admitir que aceitamos o argumento indutivista. Mesmo assim, não poderíamos aceitar a crença do Henrique sobre aquele celeiro como conhecimento.
:::

### Críticas ao Falsificacionismo {#sec-2-1-8}


### Kuhn e os Paradigmas como Critério de Demarcação {#sec-2-1-9}


### Lakatos, o Falsificacionismo Sofisticado e os Programas de Investigação {#sec-2-1-10}


### Feyerabend e a Anarquia Epistemológica {#sec-2-1-11}


### Laudan: Crítica dos Critérios de Demarcação Propostos e o Apelo para o Fim da Busca de Critérios {#sec-2-1-12}


### Pigliucci & Boudry e a Passagem de um Critério de Demarcação Wittgensteiniano para um Critério Wittgensteiniano de Demarcação {#sec-2-1-13}


### A Atitude Científica {#sec-2-1-14}


### A Demarcação da Pseudociência {#sec-2-1-15}


### O Novo Experimentalismo {#sec-2-1-16}


### A Regra de Ferro e a Minúcia Excruciante {#sec-2-1-17}


### O tratado de Tordesilhas entre Ciência e Religião ou Newton, o Alquimista {#sec-2-1-18}




