project:
  type: book
  output-dir: docs

book:
  title: "Hipótese, Contraste, Generalização e Contra-Exemplo"
  subtitle: "Filosofia da Ciência e Métodos de Inferência"
  author: "Leonel Garcia-Marques"
  language: pt
  navbar:
    pinned: true
    right:
      - text: "Baixar PDF"
      - icon: filetype-pdf
        href: HCGCE.pdf
      - text: "|"
      - text: "Ler PDF online"
      - icon: book
        href: pdf-viewer.html
      - text: "|"
      - icon: envelope-at
        href: mailto:email@email.com
  sidebar:
    title: "Índice"
  chapters:
    - index.qmd
    - 00-prologo.qmd
    - part: "---"
      chapters:
        - 01-capitulo1.qmd
        - 02-capitulo2.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: true
    lang: pt
