project:
  type: book
  output-dir: docs

book:
  title: "Hipótese, Contraste, Generalização e Contra-Exemplo"
  subtitle: "Filosofia da Ciência e Métodos de Inferência"
  author: "Leonel Garcia-Marques"
  language: pt
  navbar:
    pinned: true
    right:
      - text: "Ler online"
        icon: book
        href: 00-prologo.html
      - text: "|"
      - text: "Baixar PDF"
        href: HCGCE.pdf
      - icon: filetype-pdf
        href: HCGCE.pdf
      - text: "|"
      - text: "Ler PDF online"
        href: pdf-viewer.html
      - icon: display
        href: pdf-viewer.html
      - text: "|"
      - icon: envelope-at
        href: mailto:email@email.com
  sidebar:
    title: "Índice"
  chapters:
    - index.qmd
    - 00-prologo.qmd
    - part: "---"
      chapters:
        - 01-capitulo1.qmd
        - 02-capitulo2.qmd
        - 03-capitulo3.qmd
        - 04-capitulo4.qmd
        - 05-capitulo5.qmd
        - 06-capitulo6.qmd
        - 07-capitulo7.qmd
        - 08-capitulo8.qmd
        - 09-capitulo9.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4
    number-sections: true
    lang: pt
    include-after-body: _theme-switcher.html
